version: '2.21'

services:
  postgres_db:
    image: postgres:latest
    restart: always
    container_name: postgres_container
    volumes:
      - ./docker/pg-data:/var/lib/postgresql/data/
    command: -p 5435
    env_file:
      - .env 
    network_mode: "host"
  
  pg_admin:
    image: dpage/pgadmin4:latest
    restart: always
    container_name: pgadmin_container
    user: "${UID}:${GID}"
    volumes:
      - ./docker/pgadmin-data:/var/lib/pgadmin
    env_file:
      - .env
    depends_on:
      - postgres_db
    network_mode: "host"

volumes:
  pg_data:
  pgadmin_data:
