version: '2.21'

services:
  postgres_db:
    image: postgres:latest
    restart: always
    container_name: postgres_container
    command: -p 5432
    expose:
      - 5432
    volumes:
      - ./docker/pg-data:/var/lib/postgresql/data/
    env_file:
      - .env